services:
  mysql:
    image: mysql:8.4
    container_name: stockwise-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stockwise_inventory
      MYSQL_USER: stockwise
      MYSQL_PASSWORD: stockwise123
      MYSQL_ROOT_PASSWORD: root-stockwise123
    ports:
      - "3306:3306"
    volumes:
      - stockwise_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  stockwise_mysql_data:
